### ISSUE TITLE
gems.metaclass relies solely on Python2 metaclass behaviors

### ISSUE THREAD

**Issue by dogwynn** [bprinty/gems#2]
Getting an error in Python 3 when running nosetests on `gems` test suite.

```
======================================================================
FAIL: test_docrequire (tests.test_metaclasses.TestDocRequire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/....../gems/tests/test_metaclasses.py", line 25, in test_docrequire
    class A(object):
AssertionError: AssertionError not raised

----------------------------------------------------------------------
```

Seems that the `gems.metaclass.DocRequire` type is relying on Python2 metaclass behaviors:

```python
class A(object):
    __metaclass__ = DocRequire

    def method(self):
        return
```

I believe that the `__metaclass__` attribute is ignored in Python 3.

You will either need to use the [`six` module's metaclass functions](https://stackoverflow.com/a/39013295/1869370) or do some sort of version checking.

**Comment by bprinty** [comment]
Fixed using the six.add_metaclass decorator. Thanks for the heads up!
